/**
 * Prediction Synthesis — AI-Powered 2036 Urban Panorama Generation
 * Uses Gemini 3.1 Flash Image Preview (NanoBanana) to synthesize
 * a speculative streetscape / aerial panorama from satellite trend data.
 */

import { GoogleGenAI } from '@google/genai';
import { v2 as cloudinary } from 'cloudinary';

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

const SCENE_PROMPTS = {
  main_street: (ctx) => `Generate a highly photorealistic equirectangular 360-degree panoramic street-level view of a MAIN COMMERCIAL STREET in ${ctx.locationName || 'an urban area'} in the year 2036.

Context: Built-up density ${ctx.urbanDensity}%, ${ctx.trend} trajectory.
Scene: A vibrant pedestrian-friendly shopping avenue with smart digital storefronts, drone delivery docks, outdoor cafes, AR signage, solar pavement, and modern tram tracks. Bustling but clean. No cars in the central lane.
Style: Photorealistic, seamless 360° equirectangular, 2:1 feel, warm daylight, no text/watermarks.`,

  residential: (ctx) => `Generate a highly photorealistic equirectangular 360-degree panoramic view of a RESIDENTIAL DISTRICT in ${ctx.locationName || 'an urban area'} in the year 2036.

Context: Built-up density ${ctx.urbanDensity}%, ${ctx.trend} trajectory.
Scene: High-density eco-towers with vertical gardens, rooftop community spaces, solar glass facades, tree-lined walkways, shared EV charging stations, and children playing in safe courtyards.
Style: Photorealistic, seamless 360° equirectangular, golden hour lighting, no text/watermarks.`,

  healthcare: (ctx) => `Generate a highly photorealistic equirectangular 360-degree panoramic view of a HEALTHCARE CAMPUS in ${ctx.locationName || 'an urban area'} in the year 2036.

Context: Built-up density ${ctx.urbanDensity}%, ${ctx.trend} trajectory.
Scene: A modern medical complex with clean white-and-green architecture, healing gardens, glass atriums, patient drop-off zones with autonomous shuttles, and digital health kiosks. Calm, professional atmosphere.
Style: Photorealistic, seamless 360° equirectangular, bright natural light, no text/watermarks.`,

  education: (ctx) => `Generate a highly photorealistic equirectangular 360-degree panoramic view of an EDUCATION CAMPUS in ${ctx.locationName || 'an urban area'} in the year 2036.

Context: Built-up density ${ctx.urbanDensity}%, ${ctx.trend} trajectory.
Scene: A futuristic learning academy with open-air classrooms, maker labs with glass walls, student plazas with holographic info displays, biotech greenhouses, and skateboard/bike-friendly paths.
Style: Photorealistic, seamless 360° equirectangular, midday vibrant light, no text/watermarks.`,

  green_space: (ctx) => `Generate a highly photorealistic equirectangular 360-degree panoramic view of an URBAN PARK in ${ctx.locationName || 'an urban area'} in the year 2036.

Context: Built-up density ${ctx.urbanDensity}%, ${ctx.trend} trajectory.
Scene: A regenerated urban forest with elevated carbon-capture walkways, biodiversity ponds, community farming plots, outdoor yoga decks, solar-powered lighting, and wildflower meadows weaving between modern buildings.
Style: Photorealistic, seamless 360° equirectangular, lush greenery, soft morning light, no text/watermarks.`,

  tech_hub: (ctx) => `Generate a highly photorealistic equirectangular 360-degree panoramic view of a TECH & BUSINESS HUB in ${ctx.locationName || 'an urban area'} in the year 2036.

Context: Built-up density ${ctx.urbanDensity}%, ${ctx.trend} trajectory.
Scene: A sleek glass-and-steel innovation district with AI research towers, startup co-working terraces, autonomous vehicle lanes, drone ports on rooftops, and holographic building signage. Fast, dynamic energy.
Style: Photorealistic, seamless 360° equirectangular, twilight blue-hour with interior glow, no text/watermarks.`,
};

async function generateSinglePanorama(prompt, sceneType, index) {
  const result = await ai.models.generateContent({
    model: 'gemini-3.1-flash-image-preview',
    contents: [{ text: prompt }],
  });

  let imageBase64 = null;
  let imageMimeType = 'image/png';

  if (result.candidates && result.candidates[0]?.content?.parts) {
    for (const part of result.candidates[0].content.parts) {
      if (part.inlineData) {
        imageBase64 = part.inlineData.data;
        imageMimeType = part.inlineData.mimeType || 'image/png';
        break;
      }
    }
  }

  if (!imageBase64) {
    let reason = 'No image was generated by the AI.';
    if (result.candidates && result.candidates[0]?.content?.parts) {
      for (const part of result.candidates[0].content.parts) {
        if (part.text) { reason = part.text; break; }
      }
    }
    throw new Error(`${sceneType}[${index}]: ${reason}`);
  }

  const uploadResponse = await new Promise((resolve, reject) => {
    cloudinary.uploader.upload(
      `data:${imageMimeType};base64,${imageBase64}`,
      { folder: 'xrplot/predictions', resource_type: 'image', quality: 'auto', format: 'jpg' },
      (error, result) => {
        if (error) reject(error);
        else resolve(result);
      }
    );
  });

  return {
    url: uploadResponse.secure_url,
    publicId: uploadResponse.public_id,
  };
}

export async function synthesize2036Panorama({ lat, lng, urbanDensity, confidence, ndbiTrend, locationName }) {
  // Fail-safe: allow the pipeline/UI to work even if Gemini/Cloudinary aren't configured.
  if (!process.env.GEMINI_API_KEY) {
    return { url: '', publicId: '', generated: false };
  }

  const trendDirection = ndbiTrend[ndbiTrend.length - 1] > ndbiTrend[0] ? 'rapidly urbanizing' : 'stable or declining';
  const ctx = {
    lat, lng, urbanDensity, confidence, ndbiTrend, locationName,
    trend: trendDirection,
  };

  const prompt = `Generate a highly photorealistic equirectangular 360-degree panoramic street-level view of the urban area near coordinates (${lat.toFixed(4)}, ${lng.toFixed(4)}) in the year 2036.

Urban growth context:
- Current projected built-up density: ${urbanDensity}% of the landscape.
- Growth trajectory: ${trendDirection} over the last decade.
- Confidence in prediction: ${(confidence * 100).toFixed(0)}%.

Style guidelines:
- Modern, minimalist architectural aesthetic.
- Seamless 360° equirectangular layout (2:1 aspect ratio feel).
- Photorealistic lighting, shadows, and textures.
- Show futuristic but believable urban evolution — smart infrastructure, clean energy elements, pedestrian-friendly spaces.
- No text, no watermarks, no UI elements.

Return only the generated panoramic image.`;

  return generateSinglePanorama(prompt, 'default', 0);
}

export async function synthesizeScenePanoramas({ lat, lng, urbanDensity, confidence, ndbiTrend, locationName, hotspots }) {
  // Fail-safe: generate empty panoramas (but still create the predicted city graph)
  // when Gemini isn't configured. This keeps Next.js routes from crashing.
  if (!process.env.GEMINI_API_KEY) {
    return (hotspots || []).map((hotspot) => ({
      hotspotId: hotspot.id,
      type: hotspot.type,
      url: '',
      publicId: '',
      generated: false,
      error: 'GEMINI_API_KEY not configured',
    }));
  }

  const trendDirection = ndbiTrend[ndbiTrend.length - 1] > ndbiTrend[0] ? 'rapidly urbanizing' : 'stable or declining';
  const ctx = {
    lat, lng, urbanDensity, confidence, ndbiTrend, locationName,
    trend: trendDirection,
  };

  const results = [];
  for (let i = 0; i < hotspots.length; i++) {
    const hotspot = hotspots[i];
    const promptFn = SCENE_PROMPTS[hotspot.type] || SCENE_PROMPTS.main_street;
    const prompt = promptFn(ctx);

    try {
      const panorama = await generateSinglePanorama(prompt, hotspot.type, i);
      results.push({
        hotspotId: hotspot.id,
        type: hotspot.type,
        ...panorama,
        generated: true,
      });
    } catch (err) {
      console.warn(`Failed to generate panorama for ${hotspot.type}:`, err.message);
      results.push({
        hotspotId: hotspot.id,
        type: hotspot.type,
        url: '',
        publicId: '',
        generated: false,
        error: err.message,
      });
    }
  }

  return results;
}
