import { auth } from '@clerk/nextjs/server';
import { NextResponse } from 'next/server';
import connectDB from '@/lib/db';
import World from '@/models/World';
import { GoogleGenAI } from '@google/genai';
import { v2 as cloudinary } from 'cloudinary';

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export async function POST(request, { params }) {
  const resolvedParams = await params;
  const { worldId, nodeId } = resolvedParams;

  try {
    const { userId } = await auth();
    if (!userId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const formData = await request.formData();
    const promptText = formData.get('prompt');
    const targetImageUrl = formData.get('targetImageUrl');
    const targetImageIndex = formData.get('targetImageIndex');
    const referenceImage = formData.get('referenceImage');

    if (!promptText || !targetImageUrl) {
      return NextResponse.json({ error: 'Missing prompt or target image url' }, { status: 400 });
    }

    await connectDB();
    const world = await World.findOne({ _id: worldId, userId });
    if (!world) return NextResponse.json({ error: 'World not found' }, { status: 404 });

    const nodeIndex = world.nodes.findIndex(n => String(n.id) === String(nodeId));
    if (nodeIndex === -1) return NextResponse.json({ error: 'Node not found' }, { status: 404 });

    // Build content parts for Nano Banana (Gemini image gen)
    const contentParts = [];

    // Add text prompt
    contentParts.push({
      text: `Edit the following target image based on this instruction: "${promptText}". ${referenceImage ? 'Use the second image as a style/content reference only.' : ''} Return the edited image.`
    });

    // Add target image as inline data
    try {
      const response = await fetch(targetImageUrl);
      const arrayBuffer = await response.arrayBuffer();
      const base64 = Buffer.from(arrayBuffer).toString('base64');
      contentParts.push({
        inlineData: { data: base64, mimeType: 'image/jpeg' },
      });
    } catch (e) {
      console.warn('Failed to fetch target image:', e);
      return NextResponse.json({ error: 'Failed to fetch target image' }, { status: 400 });
    }

    // Add reference image if provided
    if (referenceImage && referenceImage.size > 0) {
      const arrayBuffer = await referenceImage.arrayBuffer();
      const base64 = Buffer.from(arrayBuffer).toString('base64');
      contentParts.push({
        inlineData: { data: base64, mimeType: referenceImage.type || 'image/jpeg' },
      });
    }

    // Call Nano Banana (gemini-3.1-flash-image-preview) using @google/genai SDK
    const result = await ai.models.generateContent({
      model: 'gemini-3.1-flash-image-preview',
      contents: contentParts,
    });

    // Extract image data from response parts
    let imageBase64 = null;
    let imageMimeType = 'image/png';

    if (result.candidates && result.candidates[0]?.content?.parts) {
      for (const part of result.candidates[0].content.parts) {
        if (part.inlineData) {
          imageBase64 = part.inlineData.data;
          imageMimeType = part.inlineData.mimeType || 'image/png';
          break;
        }
      }
    }

    if (!imageBase64) {
      // Fallback: check if there's text explaining why it failed
      let reason = 'No image was generated by the AI.';
      if (result.candidates && result.candidates[0]?.content?.parts) {
        for (const part of result.candidates[0].content.parts) {
          if (part.text) {
            reason = part.text;
            break;
          }
        }
      }
      console.error('No image in AI response:', reason);
      return NextResponse.json({ error: reason }, { status: 400 });
    }

    // Upload generated image to Cloudinary
    let newImageUrl = '';
    let newPublicId = '';

    try {
      const uploadResponse = await new Promise((resolve, reject) => {
        cloudinary.uploader.upload(
          `data:${imageMimeType};base64,${imageBase64}`,
          { folder: 'xrplot/prompts' },
          (error, result) => {
            if (error) reject(error);
            else resolve(result);
          }
        );
      });

      newImageUrl = uploadResponse.secure_url;
      newPublicId = uploadResponse.public_id;
    } catch (err) {
      console.error('Cloudinary upload error:', err);
      return NextResponse.json({ error: 'Failed to save generated image to Cloudinary' }, { status: 500 });
    }

    // Update DB - save originals for revert, then replace the target image
    if (targetImageIndex === 'panorama') {
      const node = world.nodes[nodeIndex];
      if (!node.originalPanoramaUrl) {
        node.originalPanoramaUrl = node.panoramaUrl;
        node.originalPanoramaPublicId = node.panoramaPublicId;
      }
      node.panoramaUrl = newImageUrl;
      node.panoramaPublicId = newPublicId;
    } else {
      const idx = parseInt(targetImageIndex, 10);
      const img = world.nodes[nodeIndex].images[idx];
      if (!isNaN(idx) && img) {
        if (!img.originalUrl) {
          img.originalUrl = img.url;
          img.originalPublicId = img.publicId;
        }
        img.url = newImageUrl;
        img.publicId = newPublicId;
      }
    }

    world.markModified('nodes');
    await world.save();

    return NextResponse.json({ success: true, newImageUrl });
  } catch (error) {
    console.error('Prompt Route Error:', error);
    return NextResponse.json({ error: error.message || 'Internal server error' }, { status: 500 });
  }
}
